### ISSUE TITLE
fix gender question

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/hackassistant-registration#2]
This is what it currently says:

> What gender do you associate with?
> - Prefer not to answer
> - Male
> - Female
> - Non-binary

It should say "What do you identify as?" with the following options:

![image](https://user-images.githubusercontent.com/923242/52583820-70f22e00-2e28-11e9-917d-0a241a5844c2.png)

cc @vaidap what do you think?

**Comment by qaisjp** [comment]
@ViRb3 @pkage which one of you wants to do this?

**Comment by elenalape** [comment]
I like new suggestion
