### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/hackassistant-registration#4]
![image](https://user-images.githubusercontent.com/923242/52584665-908a5600-2e2a-11e9-8b22-01fc34ccdadd.png)

do we want to do something sexy or just get rid of the outline?

@elenalape?

**Comment by elenalape** [comment]
yeah that's fine just get rid of the outline. can we have the colour scheme changed to red black?

**Comment by qaisjp** [comment]
ok, will do. as for colour scheme please check #5
