### ISSUE TITLE
theme color

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/hackassistant-registration#5]
not green anymore. red?

**Comment by qaisjp** [comment]
it looks like this now, is that fine? 
![image](https://user-images.githubusercontent.com/923242/52586023-56bb4e80-2e2e-11e9-8dfd-f5a5a2a24d7a.png)

the background looked like this before

![image](https://user-images.githubusercontent.com/923242/52586066-73578680-2e2e-11e9-86e7-6109abac2cb2.png)

**Comment by qaisjp** [comment]
@pkage thanks for the hex (on slack).

this one below (not pushed) is `#cc3333` which is a bit bright:

![image](https://user-images.githubusercontent.com/923242/52586108-91bd8200-2e2e-11e9-9fc7-7ed2c10cf791.png)

**Comment by elenalape** [comment]
isn't it a bit too coral?

**Comment by qaisjp** [comment]
which one? the kage hex code or the first screenshot in https://github.com/compsoc-edinburgh/hackassistant-registration/issues/5#issuecomment-462448817?

**Comment by elenalape** [comment]
can you try `#b71618` ?

**Comment by qaisjp** [comment]
> a bit painful to look at

^ according to bystander

![image](https://user-images.githubusercontent.com/923242/52587128-435db280-2e31-11e9-9a24-bdf4b354ee87.png)

^ that's what `#b71618` looks like 

(personally fwiw i think [the maroonish color](https://user-images.githubusercontent.com/923242/52586023-56bb4e80-2e2e-11e9-8dfd-f5a5a2a24d7a.png) is ok on the eyes)

**Comment by elenalape** [comment]
> (personally fwiw i think [the maroonish color](https://user-images.githubusercontent.com/923242/52586023-56bb4e80-2e2e-11e9-8dfd-f5a5a2a24d7a.png) is ok on the eyes)

okie, do that. thank you!

**Comment by elenalape** [comment]
can you make the blueish notification thing grey?

**Comment by qaisjp** [comment]
ok done
